<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="System.Management" Version="10.0.10" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.10" />
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
  </ItemGroup>

</Project>
